### ISSUE TITLE
Bugs opening .d files

### ISSUE THREAD

**Issue by michaelmarty** [BlaisProteomics/multiplierz#5]
Hi Team,
I found a few bugs when opening Agilent .d files, mostly related to the bruker.py file. Here are my fixes:

bruker.py

Delete izip from import. Not needed and deprecated in Python 3 apparently.
Add parentheses in print on Line 355.

__init__.py

Line 135 needs to catch other import errors: <except (COMError, IOError, OSError) as err:>

With those two changes, it seems to work fine. Hope that helps. I could try to do a pull request, but I think it's faster for you just to make those few edits. 

Thanks,
Michael Marty

**Comment by MaxAlex** [comment]
Problems with .d files should be resolved with the recent update, which rewrote the Agilent data access.
