### ISSUE TITLE
Removal of mzIntsReturnOnly flag from Bruker.py

### ISSUE THREAD

**Issue by Yatagarasu50469** [BlaisProteomics/multiplierz#9]
With the regression of the Bruker.py alterations, a boolean flag (mzIntsReturnOnly) that allows bypassing/removing unnecessary overhead from list(zip()) calls has been removed from Bruker.py, but otherwise retained in raw.py and D.py. For performance (and compatibility with SLADS/DLADS/GLANDS) it would be nice if this optional flag/behavior was retained (should be non-breaking as the default matched previous program behavior). Otherwise for feature parity it may be advisable to similarly excise the flag/behavior from the other formats.

**Comment by MaxAlex** [comment]
I've added the flag back in to mzBruker.frame(); I don't have Bruker data readily available to test on right now so let me know if there's any problems with the update.
